apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: test
  name: backenddeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: test
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate 
  template: 
     metadata:
       labels:
         environment: test
     spec:
       containers:
       - image: fernando29hernandez/backend_proyecto
         name: backendproyecto 
         ports:
           - containerPort: 3000
